highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
# ɪᴍᴩᴜᴙᴇ&nbsp;Ꞙᴜᴨ ɪᴍᴩᴜʀᴇᴆᴇᴠ ΙΜΡՍЯЕҒՍͶ iмpᴜre.fᴜn iᴍᴩᴜᴙᴇ.fᴜᴨ
# iᴍᴩᴜʀᴇfᴜn <span style="letter-spacing: -.15rem;">i</span>ᴍᴩᴜʀᴇ<span style="letter-spacing: -.25rem;">f</span>ᴜn
title:            impure.fun
title_image:      https://impure.fun/assets/2020/take-it-to-the-stars.png
tagline:          'Mostly for profit'
twitter_intro:    'Functional code for humans'
intro:            'Functional code for humans'
url:              https://impure.fun
baseurl:          '/'

author:
  name:           'Luis Ferrao'
  url:            https://twitter.com/luwvis

paginate:         3

# Custom vars
version:          1.0

theme: jekyll-theme-hacker
