highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            impure.fun
title_image:      https://impure.fun/assets/2020/take-it-to-the-stars.png
tagline:          'Mostly for profit'
twitter_intro:    'Functional code for humans'
twitter_username: luwvis
intro:            'Functional code for humans'
url:              https://impure.fun
baseurl:          '/'

author:
  name:           'Luis Ferrao'
  url:            https://twitter.com/luwvis

paginate:         3

# Custom vars
version:          1.0

# GitHub Pages
theme: jekyll-theme-hacker

unpublished: true
