highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            FᴜᴨᴐᴦɪᴏɴᴧʟFᴜᴨѕɪɵs
tagline:          'Mostly for profit'
twitter_intro:    'Mostly for profit'
intro:            'Mostly for profit'
url:              http://functionalfunsies.com
baseurl:          ""

author:
  name:           'Luis Ferrao'
  url:            https://twitter.com/luislikeIewis

paginate:         3

# Custom vars
version:          1.0

theme: jekyll-theme-hacker