highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Functional Funsies
title_stylized:   Fᴜᴨᴐᴦɪᴏᴨᴧʟ Fᴜᴨѕɪɵs
title_image:      http://functionalfunsies.com/assets/2020/take-it-to-the-stars.png
tagline:          'Mostly for profit'
twitter_intro:    'Functional code makes good apps. Good people make functional societies.'
intro:            'Functional code makes good apps.<br>Good people make functional societies.'
url:              http://functionalfunsies.com
baseurl:          ""

author:
  name:           'Luis Ferrao'
  url:            https://twitter.com/luislikeIewis

paginate:         3

# Custom vars
version:          1.0

theme: jekyll-theme-hacker