# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Functional Funsies
tagline:          'Mostly for profit'
description:      'Sometimes I write idiomatic <a href="http://fsharp.org" target="_blank">F#</a>, mostly by accident. Made by <a href="https://twitter.com/fishyrock" target="_blank">@fishyrock</a>.'
url:              http://functionalfunsies.com
baseurl:          /

author:
  name:           'Luis Ferrao'
  url:            https://twitter.com/fishyrock

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/lfr
